#!/usr/bin/env python3
import random, math, pathlib, sys
from collections import defaultdict

HOSTS_PER_LEAF = 3
LEAVES = 4
TOTAL_HOSTS = HOSTS_PER_LEAF * LEAVES

LOAD = float(sys.argv[1]) if len(sys.argv) > 1 else 0.6
MICE_FRAC = 0.8
MICE_MIN, MICE_MAX = 64*1024, 1*1024*1024
ELEPHANT_MIN = 64*1024*1024
DURATION = 50.0
SEED = 1
random.seed(SEED)

def pick_host(exclude=None):
    while True:
        h = random.randrange(TOTAL_HOSTS)
        if h != exclude:
            return h

def sample_mice():
    a, b = math.log(MICE_MIN), math.log(MICE_MAX)
    return int(math.exp(random.uniform(a, b)))

def gen_flows():
    flows, t = [], 0.0
    gap = (1.0 - LOAD) * 0.02 + 0.002  # 控制总体负载
    while t < DURATION:
        s = random.randrange(TOTAL_HOSTS); d = pick_host(s)
        size = sample_mice() if random.random() < MICE_FRAC else ELEPHANT_MIN
        flows.append((t, s, d, size))
        t += random.expovariate(1.0 / gap)
    return flows

def write_inc(flows, path):
    lines = ["# auto-generated by scripts/traffic.py"]
    by_host = defaultdict(list)
    for st, s, d, sz in flows:
        by_host[s].append((st, d, sz))
    for h, vec in by_host.items():
        lines.append(f"**.host[{h}].numApps = {len(vec)}")
        for i,(st,d,sz) in enumerate(vec):
            base=f"**.host[{h}].app[{i}]"
            lines += [
              f'{base}.typename = "TcpSessionApp"',
              f"{base}.active = true",
              f'{base}.connectAddress = "host[{d}]"',
              f"{base}.connectPort = 80",
              f"{base}.tOpen = {st:.3f}s",
              f"{base}.tSend = {st+0.010:.3f}s",
              f"{base}.sendBytes = {sz}B",
              f"{base}.tClose = {st+3600:.3f}s",
            ]
    pathlib.Path(path).write_text("\n".join(lines))

if __name__ == "__main__":
    out = pathlib.Path(__file__).resolve().parents[1] / "sim" / "flows.inc"
    write_inc(gen_flows(), out)
    print("wrote", out)
